#cn=admin,dc=seasolutions,dc=com
version: '3'
services:
  openldap:
    image: osixia/openldap:1.2.3
    container_name: openldap
    env_file:
      - environment/phpldapadmin.env
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    domainname: "seasolutions.com.br" # important: same as hostname
    hostname: "seasolutions.com.br"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9034:80"
    depends_on:
      - openldap