version: '3.7'

volumes:
  gpg_volume: 
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=172.18.32.100,rw
      device: ":/nfs/docker/passbolt/gpg_volume"
  jwt_volume: 
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=172.18.32.100,rw
      device: ":/nfs/docker/passbolt/jwt_volume"

services:
  passbolt:
    command: ["/usr/bin/wait-for.sh", "-t", "0", "172.18.32.205:3306", "--", "/docker-entrypoint.sh"]
    env_file:
      - environment/passbolt.env
    image: passbolt/passbolt:latest-ce
    ports:
    - published: 9023
      target: 80
    - published: 9022
      target: 443
    tty: true
    volumes:
      - gpg_volume:/etc/passbolt/gpg:rw
      - jwt_volume:/etc/passbolt/jwt:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
